name: Run tests
on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
     
      - name: setup
        uses: actions/checkout@v2
      
#      - name: npm setup
#        uses: ng-easy/npm-setup@v1.7.2
      
#      - name: run npm build
#        run: npm run build

      - name: Node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
#      - name: Cache npm dependencies
#        id: cache-node_modules
#        uses: actions/cache@v2
#        with:
#          path: ./node_modules
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

#      - name: Cache Cypress dependencies
#        id: cache-cypress
#        uses: actions/cache@v2
#        with:
#          path: ~/.cache/Cypress
#          key: cypress-cache-v2-${{ runner.os }}-${{
#            hashFiles('**/package-lock.json') }}

      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PA_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: install ncc
        run: apt install ncc
        
      - name: Run build
        run: npm run build

      - name: Run tests and coverage
        run: npm run test:coverage
